grpc:
  client:
    authentication-grpc-service:
      address: static://localhost:9001
      negotiationType: plaintext
    post-grpc-service:
      address: static://localhost:9003
      negotiationType: plaintext

server:
  port: 8000



