grpc:
  client:
    authentication-grpc-service:
      address: 'static://authentication-grpc-service:9001'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    connection-grpc-service:
      address: 'static://connection-grpc-service:9002'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    post-grpc-service:
      address: 'static://post-grpc-service:9003'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    notification-grpc-service:
      address: 'static://notification-grpc-service:9004'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    message-grpc-service:
      address: 'static://message-grpc-service:9005'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    job-offer-grpc-service:
      address: 'static://job-offer-grpc-service:9006'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 8000





