grpc:
  client:
    authentication-grpc-service:
      address: static://localhost:9001
      negotiationType: plaintext
    connection-grpc-service:
      address: static://localhost:9002
      negotiationType: plaintext
server:
  port: 8000