grpc:
  client:
    authentication-grpc-service:
      address: static://localhost:9001
      negotiationType: plaintext
    connection-grpc-service:
      address: static://localhost:9002
      negotiationType: plaintext
    post-grpc-service:
      address: static://localhost:9003
      negotiationType: plaintext
    notification-grpc-service:
      address: static://localhost:9004
      negotiationType: plaintext

server:
  port: 8000





