version: "3"
services:
  authentication_service:
    container_name: authentication_service
    hostname: authentication-grpc-service
    networks:
      - auth_database_net
      - backend_net
    build:
      context: ./authentication_service
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8001:8001
      - 9001:9001
  api_gateway:
    container_name: api_gateway
    networks:
      - backend_net
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile
    environment:
      AUTH_HOST: authentication_service
      AUTH_GRPC_PORT: 9001
    ports:
      - 8000:8000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - auth_database_net
    ports:
      - 27017:27017

networks:
  backend_net:
    driver: bridge
  auth_database_net:
    driver: bridge