version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  authentication_service:
    image: authentication_service.jar
    container_name: authentication_service
    build: .
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.database=users
      - grpc.server.port=9001
    depends_on:
      - mongodb
    ports:
      - "9001:9001"
  api_gateway:
    image: api_gateway.jar
    container_name: api_gateway
    build: .
    environment:
      AUTH_HOST: authentication_service
      AUTH_GRPC_PORT: 9001
    ports:
      - "8000:8000"

