version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: MONGODB
    ports:
      - 27017:27017
  api_gateway:
    image: api_gateway.jar
    container_name: API_GATEWAY
    ports:
      - 8000:8000
      - 9090:9090
  authentication_service:
    image: authentication_service.jar
    container_name: AUTHENTICATION_SERVICE
    ports:
      - 8001:8001
      - 9001:9001
