grpc:
  server:
    port: 9001

server:
  port: 8001

spring:
  data:
    mongodb:
      host: mongodb
      uri: mongodb://127.0.0.1:27017
      database: users
      repositories:
        enabled: true