grpc:
  server:
    port: 9001
    
server:
  port: 8001

spring:
  data:
    mongodb:
      host: mongodb
      uri: mongodb://localhost:27017
      database: users
      repositories:
        enabled: true