grpc:
  server:
    port: 9002

server:
  port: 8002

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: connections
    neo4j:
      uri: neo4j://localhost:7687
      database: neo4j
      authentication:
        username: neo4j
        password: firma4