grpc:
  server:
    port: 9002

server:
  port: 8002

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: connections
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
